services:
  - type: web
    name: descoinfo
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ACCOUNT_NO
        sync: false
      - key: CHAT_ID
        sync: false
      - key: LOW_BALANCE_LIMIT
        value: "100"
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: "10000"
