services:
  - type: web
    name: descoinfo
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: "10000"
      - key: ADMIN_ID
        sync: false
